apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-announcement-policy
spec:
  loadBalancerIPs: true
  interfaces:
  - "^eth[0-9]+$"
  - "^enp[0-9]+s[0-9]+$"
  - "^enx[a-f0-9]+$"